name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Images
        run: echo "Simulación de construcción de imágenes Docker"

      - name: Run Tests
        run: echo "Simulación de pruebas unitarias"

      - name: Deploy to ECS
        run: echo "Simulación de despliegue a ECS"
